# Data Storage Settings
database:
  enabled: false # If false, data is stored as files
  host: "localhost"
  port: 3306
  database: "biomemastery"
  username: "root"
  password: ""

settings:
  # In seconds, how often should players be checked for the biome duration threshold
  # Recommended no less than 10 seconds. Bigger servers should have a higher interval
  # Default: 60
  update_interval: 60

  # In seconds, what is the cooldown for any command that triggers player data to be updated
  # The commands: /biome info, /biome <biome>
  # Must be 1 second or higher
  # Default: 3
  command_cooldown: 3

  # Do you want there to be a notification given in console when there is an update available
  # Default: true
  plugin_update_notification: true

default_biome_settings:
  # List the worlds you want this plugin to work on
  enabled_worlds:
    - 'world'

  # Set this to false if you want to use the blacklist list as a blacklist
  # Set this to true if you want to use the blacklist list as a whitelist instead
  # Default: false
  use_blacklist_as_whitelist: false

  # If the above setting is false: List biomes that you DON'T want rewards for
  # If the above setting is true: List biomes that you DO want rewards for
  biomes_blacklist:
    - PLAINS

  # The default settings for each biomes rewards/levels.
  # If the Biome is not specified in the "biomes" section
  # these settings will automatically apply.
  levels:
    '1':
      type: multi-use # Valid types: singular or multi-use (Only needed for potion + effect reward types)
      target_duration: 60 # seconds
      reward_type: potion # Valid types: potion, effect, item, permission, command, experience, currency, null
      reward_item: jump:2 #potion effect:amplifier:duration
    '2':
      type: singular # Valid types: singular or multi-use (Only needed for potion + effect reward types)
      target_duration: 60 # seconds
      reward_type: potion # Valid types: potion, effect, item, permission, command, experience, currency, null
      reward_item: jump:2 #potion effect:amplifier:duration

# Anything set in here will override the default settings
# Use this if you want specific perks for a certain biome
# Make sure the biome name is from this list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
biomes:
  # Multi-use rewards are rewards that a player can activate/deactivate whenever they want whilst in the specific biome.
  # For example, if a player is at level 2 for the plains biome (see below),
  # they will be able to activate night vision every single time they're in that biome in the future
  #
  # Singular rewards are rewards that are received only once.
  #
  # Regardless if the reward is singular or multi-use, if it's a potion or effect reward type, it will
  # be removed once the player leaves that biome

  FOREST:
    '1':
      type: multi-use # Valid types: singular or multi-use (Only needed for potion + effect reward types)
      target_duration: 60 # seconds
      reward_type: potion # Valid types: potion, effect, item, permission, command, experience, currency, null
      reward_item: jump:2 #potion effect:amplifier
    '2':
      type: singular # Valid types: singular or multi-use (Only needed for potion + effect reward types)
      target_duration: 60 # seconds
      reward_type: effect # Valid types: potion, effect, item, permission, command, experience, currency, null
      reward_item: free_food # Valid effects: speed_swimmer, lava_swimmer, free_food
    '3':
      target_duration: 60 # seconds
      reward_type: item
      reward_item: apple:5 # material:quantity

  PLAINS:
    '1':
      type: multi-use # Valid types: singular or multi-use (Only needed for potion + effect reward types)
      target_duration: 60 # seconds
      reward_type: potion # Valid types: potion, effect, item, permission, command, experience, currency, null
      reward_item: jump:2 #potion effect:amplifier
    '2':
      type: singular # Valid types: singular or multi-use (Only needed for potion + effect reward types)
      target_duration: 60 # seconds
      reward_type: effect # Valid types: potion, effect, item, permission, command, experience, currency, null
      reward_item: speed_swimmer # Valid effects: speed_swimmer, lava_swimmer, free_food
    '3':
      target_duration: 60 # seconds
      reward_type: item
      reward_item: apple:5 # material:quantity
    '4':
      target_duration: 60
      reward_type: currency
      reward_item: 2000 # Amount
    '5':
      target_duration: 60
      reward_type: command
      reward_item: give %player% apple 2 # Use placeholder %player%
      reward_description: '&dCustom &6Description' # 'reward_description' Only valid on command reward types
    '6':
      target_duration: 60
      reward_type: experience
      reward_item: 10 # How many experience levels to give

  FLOWER_FOREST:
    '1':
      type: singular
      target_duration: 60
      reward_type: potion
      reward_item: jump:2
    '2':
      type: singular
      target_duration: 60
      reward_type: effect
      reward_item: lava_swimmer
    '3':
      target_duration: 60
      reward_type: item
      reward_item: apple:5
    '4':
      target_duration: 60
      reward_type: experience
      reward_item: 10
    '5':
      target_duration: 60
      reward_type: command
      reward_item: give %player% apple 2
      reward_description: '&dCustom &6Description'

